import React, { useState } from "react";
import Head from "next/head";
import {
    Container,
    VStack,
    Heading,
    ButtonGroup,
    Button,
} from "@chakra-ui/react";
import { ArrowBackIcon } from "@chakra-ui/icons";
import { Formik, Form } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import LoginInput from "./sub/loginInput";
import { useLoginMutation } from "../../../../generated/graphql";
import StatusText from "./sub/statusText";
import { ApolloError } from "apollo-server-micro";

const Login = () => {
    const router = useRouter();
    const [loginMutation] = useLoginMutation({
        notifyOnNetworkStatusChange: true,
    });
    const [errMsg, setErrMsg] = useState<string | undefined>();
    return (
        <Container h="100vh">
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Formik
                initialValues={{
                    username: "",
                    email: "",
                    password: "",
                    confirm: "",
                }}
                validationSchema={Yup.object({
                    username: Yup.string()
                        .required("Username is required")
                        .min(6, "Username too short"),
                    password: Yup.string()
                        .required("Password is required")
                        .min(6, "Password too short"),
                })}
                onSubmit={async (values, actions) => {
                    const creds = { ...values };
                    actions.resetForm();
                    try {
                        const { data } = await loginMutation({
                            variables: {
                                credentials: {
                                    username: creds.username,
                                    password: creds.password,
                                },
                            },
                        });
                        router.push("/");
                    } catch (error) {
                        setErrMsg((error as ApolloError).username);
                    }
                }}
            >
                <VStack h="100%" justify="center">
                    <VStack as={Form} shadow="2xl" w="100%" bg="gray.50" p="4">
                        <Heading>Login</Heading>
                        <StatusText errMsg={errMsg}></StatusText>
                        <LoginInput name="username" label="Username" />
                        <LoginInput
                            name="password"
                            type="password"
                            label="Password"
                        />
                        <ButtonGroup
                            colorScheme="purple"
                            w="100%"
                            size="lg"
                            pt="4"
                        >
                            <Button
                                variant="outline"
                                w="100%"
                                onClick={() => router.back()}
                                leftIcon={<ArrowBackIcon />}
                            >
                                Back
                            </Button>
                            <Button w="100%" type="submit">
                                Login
                            </Button>
                        </ButtonGroup>
                    </VStack>
                </VStack>
            </Formik>
        </Container>
    );
};

export default Login;
